project/apps/accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views


app_name = 'accounts'

urlpatterns = [
    path(
        'profile', 
        views.AccountProfileView.as_view(), name='profile'
    ),
    path(
        'auth/login', 
        auth_views.LoginView.as_view(template_name='accounts/auth/login.html'), 
        name='login'
    ),
    path(
        'auth/login/done', 
        TemplateView.as_view(template_name = 'accounts/auth/login_done.html'),
        name = 'login_done'
    ),
    path(
        'auth/logout', 
        auth_views.LogoutView.as_view(template_name='accounts/auth/logout.html'), 
        name='logout'
    ),
    path(
        'auth/logout/done', 
        TemplateView.as_view(template_name = 'accounts/auth/logout_done.html'),
        name = 'logout_done'
    ),
    path(
        'auth/signup', 
        views.SignupView.as_view(), 
        name = 'signup'
    ),
    path(
        'auth/signup/done', 
        TemplateView.as_view(template_name='accounts/auth/signup_done.html'), 
        name = 'signup_done'
    ),
    path(
        'auth/password_reset/', 
        auth_views.PasswordResetView.as_view(
            template_name='accounts/auth/password_reset.html',
            email_template_name = 'accounts/auth/password_reset_email.html',
            success_url = reverse_lazy('accounts:password_reset_done')
        ), 
        name='password_reset'
    ),
    path(
        'auth/password_reset/done/', 
        auth_views.PasswordResetDoneView.as_view(
            template_name = 'accounts/auth/password_reset_done.html'
        ), 
        name='password_reset_done'
    ),
    path(
        'auth/reset/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name = 'accounts/auth/password_reset_confirm.html',
            success_url = reverse_lazy('accounts:password_reset_complete')
        ), 
        name='password_reset_confirm'
    ),
    path(
        'auth/reset/done/', 
        auth_views.PasswordResetCompleteView.as_view(
            template_name = 'accounts/auth/password_reset_complete.html'
        ), 
        name='password_reset_complete'
    ),
    path(
        'auth/password_change/', 
        auth_views.PasswordChangeView.as_view(), 
        name='password_change'
    ),
    path(
        'auth/password_change/done/', 
        auth_views.PasswordChangeDoneView.as_view(), 
        name='password_change_done'
    ),
]

project/apps/ingredients/urls.py
from django.urls import path
from . import views

app_name = 'ingredients'

urlpatterns = [
    path('', views.IngredientsList.as_view(), name='list'),
    path('<int:id>', views.IngredientDetail.as_view(), name='detail')
]

project/apps/recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipesList.as_view(), name='list'),
    path('<int:id>', views.RecipeDetail.as_view(), name='detail')
]

project/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.landing.urls')),
    path('api/v1/ingredients/', include('apps.ingredients.urls')),
    path('api/v1/recipes/', include('apps.recipes.urls')),
    path('accounts/', include('apps.accounts.urls')),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

project/templates/core/layout.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{% block styles %}
<link href="{% static 'css/core.css' %}" crossorigin="anonymous" rel="stylesheet">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">  
{% endblock styles %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon-32.png' %}"/>
<title>Figline-Admin</title>
</head>
<body>
{% block modals %}{% endblock modals %}
<div class="app">
  <nav class="topnav">
    <a class="topnav__brand" href="/"></a>
    <div class="topnav__content" id="topnav-content">
      <ul class="topnav__menu">
        <li>
          <a class="link black" href="/">inicio</a>
        </li>
        {% if request.user.is_authenticated %}
          <li>
            <a class="link black" href="{% url 'ingredients:list' %}">ingredients</a>
          </li>
          <li>
            <a class="link black" href="{% url 'recipes:list' %}">recipes</a>
          </li>
        {% endif %}
      </ul>
      <ul class="topnav__menu">
      {% if request.user.is_authenticated %}
        <li>
          <a class="link black" href="{% url 'accounts:logout' %}">logout</a>
        </li>
        <li>
          <a class="link black" href="{% url 'accounts:profile' %}">
            <i class="material-icons">account_circle</i>
            <span>account</span>
          </a>
        </li>
        <li>
          <a class="link black" href="/admin">
            <i class="material-icons">settings</i>
          </a>
        </li>
      {% else %}
        <li>
          <a class="link black" href="{% url 'accounts:login' %}"><i class="material-icons">account_circle</i> login</a>
        </li>
      {% endif %}
      </ul>
    </div>
    <button class="topnav__toggler" data-event="topnav:toggle">
      <i class="material-icons">menu</i>
    </button>
  </nav>
  <div class="app-content">
    {% block content %}{% endblock content %}
  </div>
</div>
{% block scripts %}
<script src="{% static 'js/core.bundle.js' %}"></script>
{% endblock scripts %}
</body>
</html>